version: '3'
services:
    web:
        build: .
        command: "bash docker-entrypoint.sh"
        restart: unless-stopped
        ports:
            - 5000:5000
        links:
            - postgres:postgres
        volumes:
            - ./:/app:z
            - ./gunicorn_socket:/tmp
            - ./media:/app/media

    postgres:
        restart: always
        env_file: env.env          
        image: postgres:latest
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        
    broker:
        image: rabbitmq:3
        env_file: env.env
        ports:
            - 5672:5672
    
    celery:
        build: .
        command: celery -A router.celery worker --loglevel=info
        depends_on:
            - broker

    celery-beat:
        build: .
        command: celery -A router.celery beat --loglevel=info
        depends_on:
            - broker

    nginx:
        image: nginx:1.19.0-alpine
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./build:/home/build
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
    postgres_data: