version: '3'
services:
    web:
        build: .
        command: gunicorn --bind 0.0.0.0:5000 manage:app
        restart: always
        # ports:
        #     - "5000:5000"
        expose:
            - 5000
        links:
            - postgres:postgres
    postgres:
        restart: always
        environment:
                POSTGRES_DB: "SE"
                POSTGRES_PASSWORD: "se23571113"
                POSTGRES_USER: "postgres"
        image: postgres:latest
        volumes:
        - ./postgresData/:/var/lib/postgresql/data
        ports:
        - "5432:5432"
    nginx:
        build: ./nginx
        ports:
            - 1337:80
        depends_on:
            - web